/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adcworks.jmvs;

import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.util.Properties;

import com.adcworks.jmvs.gui.*;

/**
 * Java3D Molecular Visualisation System 4
 */
public class App extends Frame {
        
    /**
     * Boot JMVS application.
     * @param args
     */
    public static void main(String[] args) {
        new App();
    }
    
    /**
     * Create JMVS application, initialise frame and add core JMVS Panel.
     *
     */
    public App() {
        super("Java3D Molecular Visualisation System");
        
        // setup window size and location
        
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int w = screenSize.width / 2;
        int h = screenSize.height / 2;
        
        setLayout(new BorderLayout());                
        setSize(w, h);
        setLocation(screenSize.width / 2 - w / 2, screenSize.height / 2 - h / 2);
        setResizable(true);
        
        // add window listener
        
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent event) {
                System.exit(0);
            }
        });
        
	    // load jmvs properties
	    
	    Properties jmvsProperties = null;
	    
      	try {
      	    jmvsProperties = new Properties();
	        ClassLoader loader = Thread.currentThread().getContextClassLoader();
	        java.io.InputStream is = 
	            loader.getResourceAsStream("jmvs.properties");
	        
	        if (is == null) {
	        	System.out.println("Error: Could not load jmvs.properties.");
		   		System.exit(0);
	        }
	        
	        jmvsProperties.load(is);
		   	
        } catch (IOException ioE) {
            System.out.println("Error: Could not load jmvs.properties.");
            System.exit(0);
        }        			   	
		   	
	   	if (jmvsProperties.size() == 0) {
	   		System.out.println("Error: jmvs.properties was empty.");
	   		System.exit(0);
	   	}        
        
        
        // add JMVS panel
        
        JMVSPanel jmvsPanel = new JMVSPanel(this, jmvsProperties);
        add(jmvsPanel);
        setVisible(true);      
        
        // while(true) {
        //     ;
        // }

        // JMVSAbout about = new JMVSAbout(this);
        // about.setVisible(true);        
    }
}
        


